### ISSUE TITLE
Some type of constant variable keyword

### ISSUE THREAD

**Issue by srchulo** [iamalnewkirk/do#256]
Most modern languages have a way to make something constant (final, immutable, etc). Perl has

```
use constant PI => 3.14;
```

But this has the downsides of having no sigil in front (harder to interpolate in strings, and also read in code), and it's also slower since it's really a subroutine call. In `Data::Object`'s spirit of providing a framework for modern perl development, I wonder if it would make sense to export something like [const ](https://metacpan.org/pod/Const::Fast#const-$var,-$value) from  [Const::Fast](https://metacpan.org/pod/Const::Fast)?

**Comment by jjatria** [comment]
> it's also slower since it's really a subroutine call

I'm not sure this is the case. From [the documentation on `constant`](https://metacpan.org/pod/constant) (emphasis mine):

> When a constant is used in an expression, _Perl replaces it with its value at compile time_, and may then optimize the expression further. 

You can see this in action:

```
$ perl -MO=Deparse -e 'use constant PI => 3.14; print PI; print PI * PI'
use constant ('PI', 3.14);
print 3.14;
print 9.8596;
-e syntax OK
```

The value is replaced at compile-time, so there's no subroutine call at runtime to impact performance.

**Comment by iamalnewkirk** [comment]
@jjatria @srchulo Since the "constant" pragma is core, I think we should encourage people to use that, and maybe document how in POD.

Upon looking into this, I noticed that Const::Fast says, "This module was written because I stumbled on some serious issues of Readonly that aren't easily fixable without breaking backwards compatibility in subtle ways." 😬

We actually depend on Readonly for D/O/R/Immutable which is used by D/O/Struct. Maybe we should ditch Readonly for Const::Fast and used that to also enforce immutability with the added benefit that we get a "const" keyword.

**Comment by srchulo** [comment]
@jjatria That is very cool! thanks for pointing that out. Seems like that would be hard to beat performance-wise :) My only issue with it then is the lack of sigil, but I guess there's no way to get around that.

@iamalnewkirk ah, good catch. Yes, I started using `Const::Fast` instead of `Readonly`. I think it would be a good idea to switch-- both performance-wise, and correctness-wise:

> In particular Readonly's use of ties is a source of subtle bugs and bad performance. Instead, this module uses the builtin readonly feature of perl, making access to the variables just as fast as any normal variable without the weird side-effects of ties.

**Comment by srchulo** [comment]
It looks like `const` is listed as a keyword in `Data::Object::Export`, but it seems like it was deleted in #293: 

`Undefined subroutine &Data::Object::Export::const called`

**Comment by iamalnewkirk** [comment]
@srchulo Thanks; on it!

**Comment by iamalnewkirk** [comment]
This project has been deprecated in favor of https://metacpan.org/release/Data-Object and other separate releases!
