### ISSUE TITLE
Data::Object::Hash::Func::Slice - confusing name

### ISSUE THREAD

**Issue by srchulo** [iamalnewkirk/do#268]
I think that [Data::Object::Hash::slice](https://metacpan.org/pod/Data::Object::Hash#slice) may be a confusing name. In perl, there are two types of hash slices:

```
my %hash = (
    a => 'b',
    c => 'd',
);
```

- [value slice](https://perlmaven.com/hash-slice)

```
my ($a, $c) = @hash{qw/a c/};

# $a holds 'b'
# $c holds 'd'
```

- [keyvalue slice](https://www.effectiveperlprogramming.com/2014/07/perl-5-20-introduces-keyvalue-slices/)
```
my @keyvalue_slice = %hash{qw/a c/};

# @keyvalue_slice holds 'a', 'b', 'c', 'd'
```

The current `slice` method is almost like perl 5.20's keyvalue slice, but it wraps it in a hashref.

**Comment by iamalnewkirk** [comment]
I don't think the name is confusing, after all, it gives you a _"slice"_ of the original value. Slice doesn't refer to some core function or particular implementation. What would you expect the return value to be?

**Comment by srchulo** [comment]
I would expect the return value to be the value slice, so the values corresponding to the keys you passed in returned as a list. For the `Data::Object::Hash::slice` documentation example, I would expect:

```
# given {1..8}
 
my @values = $hash->slice(1,5); # (2, 6) instead of {1=>2,5=>6}
```

Here is the official perldoc that defines a [hash slice](https://perldoc.perl.org/perldata.html#Slices).

I think that `Data::Object::Hash::slice` as it's defined now is also useful, but I just think it's confusing since a `slice` on a `hash` already has a defined behavior in the perl docs.

**Comment by iamalnewkirk** [comment]
I see. FWIW, the [values](https://metacpan.org/pod/Data::Object::Hash#values) method does that. I know that we need both behaviors, i.e. there are times when you just want the values, and times when you want to easily reduce the list. Can you propose better names?

**Comment by srchulo** [comment]
Ah, thanks for pointing that out-- I didn't see that. I think those two names are good, except for when it comes to what they mean in Perl. As discussed above for `slice`, and for [values](https://perldoc.perl.org/functions/values.html) when used on a hash in perl traditionally means all values:

> returns a list consisting of all the values of the named hash

Although I do see that with no arguments `Data::Object::Hash::values` does behave this way.

Maybe `slice` and `kv_slice` or `kvslice`, since `Data::Object::Hash::values` corresponds to a traditional perl hash slice, and `Data::Object::Hash::slice` corresponds to the key value slice introduced in perl 5.20.

Also, is there a reason that `Data::Object::Hash::values` returns an array reference, and `Data::Object::Hash::slice` returns a hash reference? Is it so that they're chainable? I think that is a good reason, but could also be confusing for someone coming from traditional perl where they expect both to return a list when called on a hash:

```
my @sliced_values = @hash{qw/key1 key2/};

my %sliced_keys_and_values = %hash{qw/key1 key2/};
```

It might totally make sense the way that they are now-- I was just curious for the reasoning.

**Comment by iamalnewkirk** [comment]
@srchulo Yes, for chainability, all data object methods return a single object. I'm not sure that we disagree on anything actually, or that there's anything to change here. All the desired behaviors already exist, it's just a slight matter of naming and learning the API. Do you disagree?

**Comment by srchulo** [comment]
Yeah, I mostly agree. I still think that it's confusing that `values` and `slice` don't line up with Perl's native `values` and `slice` for hashses, However, if you think the names are appropriate now and users of `Data::Object` just need to learn that API for hashes, that's fine with me.

**Comment by iamalnewkirk** [comment]
@srchulo On this, I'll accept a PR with the discussed changes in API, since this distro is still pre-stability policy, but I don't feel strongly enough to implement the changes myself 😎

**Comment by iamalnewkirk** [comment]
@srchulo Let me know if you intend to push a PR, or if I should close this!

**Comment by srchulo** [comment]
@iamalnewkirk I do intend to do one. I've gotten started, and I'll try to get it in soon 👍
