### ISSUE TITLE
Data::Object::Role::Dumpable - say_pretty, print_pretty, dump_pretty

### ISSUE THREAD

**Issue by srchulo** [iamalnewkirk/do#271]
I was wondering if you thought it might be a good idea to add "pretty" versions of `say`, `print`, and `dump` in [Data::Object::Role::Dumpable](https://metacpan.org/pod/Data::Object::Role::Dumpable)? When I'm printing a variable, it's often for debug purposes to see what it contains, which is hard when `$Data::Dumper::Indent` is set to `0`. I was wondering what your thoughts are on this?

**Comment by iamalnewkirk** [comment]
@srchulo, I like this idea a lot! Do you want to try adding it, or do you want me to implement it?

**Comment by srchulo** [comment]
I'll take a shot at it!
