### ISSUE TITLE
deref method for Data::Object::Array and Data::Object::Hash

### ISSUE THREAD

**Issue by srchulo** [iamalnewkirk/do#284]
#268 Got me thinking about how if you want to get all values of an array or a hash as a list, there's no method to do it:

```
my @values = @$array;
my %keys_and_values = %{$hash};
```

I was wondering if you think there would be any value to something like a `deref` method?

```
my @values = $array->deref;
my %keys_and_values = $hash->deref;
```

**Comment by iamalnewkirk** [comment]
Hash and Array both have a `list` method which does what you want. I just realized that the documentation isn't clear. The list method returns a list in array context, and a reference which a shallow copy in scalar context.

This allows you to do:

```perl
for my $item ($array->list) {
  #...
}
```

and

```perl
while (my ($k,$v) = each $hash->list) {
  #...
}
```

**Comment by srchulo** [comment]
Ah, yes. The current documentation makes it seem like it's just a reference that is returned. Would you mind explaining how in list context it is returned as a list? This is what I see in `Data::Object::Array::Func::List`:

```
sub execute {
  my ($self) = @_;
 
  my ($data) = $self->unpack;
 
  return [@$data];
}
```

And in `Data::Object::Array::Func::List`:

```
sub execute {
  my ($self) = @_;
 
  my ($data) = $self->unpack;
 
  return [%$data];
}
```

Where they both return array references. I do see that `Data::Object::Array` and `Data::Object::Hash` have their own list methods. Do these delegate to the functors?

**Comment by iamalnewkirk** [comment]
I didn't realize but the List.pm functors aren't being used. E.g. see, https://github.com/iamalnewkirk/do/blob/24079d08bca895839394383f122ae7e988c985da/lib/Data/Object/Array.pm#L38

**Comment by iamalnewkirk** [comment]
This project has been deprecated in favor of https://metacpan.org/release/Data-Object and other separate releases!
