### ISSUE TITLE
List::UtilsBy functions for arrays

### ISSUE THREAD

**Issue by srchulo** [iamalnewkirk/do#309]
I was thinking it could be a good idea to at the [List::UtilsBy](https://metacpan.org/pod/List::UtilsBy) functions as methods for [Data::Object::Array](https://metacpan.org/pod/Data::Object::Array). But if we did include this, would you rather re-implement these to not add another dependency? The nice thing if we used `List::UtilsBy` directly is that anyone who had [List::UtilsBy::XS](https://metacpan.org/pod/List::UtilsBy::XS) installed would see those speed gains.

**Comment by iamalnewkirk** [comment]
@srchulo I think I'd prefer to see something like this as a separate distribution, using the plugin system mentioned in #260. e.g. Maybe **Data-Object-Plugin-ListUtilsBy**

In general, I'd like to keep the core as-is, or even make it smaller. In fact, I'd love for some to do some kind of analysis and suggest what could be moved out of the core and into plugins.

**Comment by srchulo** [comment]
@iamalnewkirk I think that's a good idea.

I hope if `Do` is made smaller, nothing useful is removed! :) Or would it maybe just be moved into something like the plugins that you mention?

**Comment by iamalnewkirk** [comment]
If anything is removed, yes, it would be released as a separate plugin. At some point soon I would like to lock the API and focus on performance and stability.

**Comment by iamalnewkirk** [comment]
This project has been deprecated in favor of https://metacpan.org/release/Data-Object and other separate releases!
